# Generated by Django 4.2.16 on 2025-11-08 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Área de Atuação',
                'verbose_name_plural': 'Áreas de Atuação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Personal Trainer, Fisioterapeuta, Nutricionista', max_length=120)),
                ('descricao', models.TextField(help_text='Fale um pouco sobre seu trabalho e formação.')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_por_sessao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avaliacao_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('area_atuacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='appPerfil.areaatuacao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profissional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Profissional',
                'verbose_name_plural': 'Perfis Profissionais',
                'ordering': ['usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='ImagemPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='perfis/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='appPerfil.perfilprofissional')),
            ],
            options={
                'verbose_name': 'Imagem do Perfil',
                'verbose_name_plural': 'Imagens do Perfil',
                'ordering': ['ordem'],
            },
        ),
    ]
