# Generated by Django 4.2.16 on 2025-11-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPerfil', '0002_availabilityslot_tiposdeareas_turma_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='student',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='slot',
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
